version: "3.9"

services:
  mongo-beaver:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo --host localhost --username root --password 1234 --quiet
      interval: 15s
      timeout: 5s
      retries: 3
    restart: always
    networks:
      - mongo_network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongo-beaver
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    depends_on:
      - mongo-beaver
    networks:
      - mongo_network

  beaver-audience-backend:
    image: natekrth/beaver-audience-app-backend:1.0
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4004/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "4004:4004"
    environment:
      DB_HOST: mongo-beaver
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: mongo-beaver
      DB_PORT: 27017
      SERVER_PORT: 4004
      JWT_SECRET: JWT_SECRET
      DB_DATABASE_Public_URL: mongodb+srv://BeaverGroup:peT0rKwlPjPyYCR2@beaver.piraenz.mongodb.net/UserDB
  
      FRONTEND_IP: "http://3.27.37.55:4005"
    depends_on:
      - mongo-beaver
   
    networks:
      - mongo_network
  beaver-audience-frontend:
    image: rew1234/beaver-audience-application-backend:VF
    ports:
      - "4005:4005" 
    environment:
      SERVER_PORT: 4005
      SERVER_HOST: "0.0.0.0"
      VITE_API_PORT: 4004
      VITE_API_HOST_IP: "3.27.37.55"
      VITE_GOOGLE_CLIENT_ID: 684559178288-ma6f967proboh0gh1jntpcnenfjttoe3.apps.googleusercontent.com
      VITE_IOC_API: https://nongnop.azurewebsites.net/match_table
      
    depends_on:
      - beaver-audience-backend  
    networks:
      - mongo_network
networks:
  mongo_network:
    driver: bridge

volumes:
  mongo_data: