version: "3.9"

services:
  mongo-beaver:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo --host localhost --username root --password 1234 --quiet
      interval: 15s
      timeout: 5s
      retries: 3
    restart: always
    networks:
      - mongo_network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongo-beaver
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 1234

    depends_on:
      - mongo-beaver
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  mongo_data:
